# @package _global_
defaults:
 - _self_

target: nacc
task: classification

num_classes: 3
weights:
live_loading: True
delete_segmentation: False
balanced_accuracy: False
eval_metric: auc # auc
data_orig:
low_data_splits: ['']

# num of features
num_cat: 0
num_con: 21


labels_train: labels_train.pt
labels_val: labels_val.pt

data_train_imaging: train_path.pt
data_val_imaging: val_path.pt

data_train_tabular: train.csv
data_val_tabular: val.csv

field_lengths_tabular: tabular_length.pt


data_train_eval_tabular: train.csv
labels_train_eval_tabular: labels_train.pt

data_val_eval_tabular: val.csv
labels_val_eval_tabular: labels_val.pt

data_test_eval_tabular: test.csv
labels_test_eval_tabular: labels_test.pt


data_train_eval_imaging: train_path.pt
labels_train_eval_imaging: labels_train.pt

data_val_eval_imaging: val_path.pt
labels_val_eval_imaging: labels_val.pt

data_test_eval_imaging: test_path.pt
labels_test_eval_imaging: labels_test.pt




